######################## default configuration ####################
baseURL = "https://kenayah.github.io/soulFood/"
languageCode = "en-us"
title = "soulFood sa"
theme = "restaurant-hugo"
summaryLength = "10"
pagination.pagerSize = 4


