name = "soulfood"
main = "src/index.tsx"
compatibility_date = "2025-01-01"

[assets]
directory = "./static"

[vars]
SITE_BASE_URL = "https://kenayah.github.io/soulFood"

[[d1_databases]]
binding = "DB"
database_name = "soulfood"
database_id = "00000000-0000-0000-0000-000000000000"

[env.dev]
[[env.dev.d1_databases]]
binding = "DB"
database_name = "soulfood-dev"
database_id = "00000000-0000-0000-0000-000000000001"
